workspace:
  base: /test
  path: bw_d7

services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    environment:
    - DOCUMENT_ROOT=/test/bw_d7
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    volumes:
#    - /cache:/cache
    commands:
      - echo "testing WIP RUNNING STEP Composer-install-lowest"
      - composer install --ansi --no-suggest --no-progress
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  composer-install-highest:
    group: prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
#    volumes:
#      - /cache:/cache
    commands:
      - echo 'Testing pipeline.composer-install-highest'
      - composer install --ansi --no-suggest --no-progress
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  run-test-with-grump:
      group: test
      image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
      commands:
        - ./vendor/bin/grumphp run --ansi

matrix:
  PHP_VERSION:
  - 5.6
  - 7.1
  - 7.2
  COMPOSER_BOUNDARY:
  - lowest
  - highest
