workspace:
  base: /test
  path: bw_d7

services:
  - name: web
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    environment:
      DOCUMENT_ROOT: /test/bw_d7
  - name: mysql
    image: percona/percona-server:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  - name: selenium
    image: selenium/hub
  - name: chrome
    image: selenium/node-chrome
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: :99.0
  - name: firefox
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: :98.0

kind: pipeline
name: default

steps:
  - name: composer-install-lowest
    group: prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    file: .env
    volumes:
    # - /cache:/cache
    commands:
      - echo "testing WIP RUNNING STEP Composer-install-lowest"
      - echo ${SECRET_URL}
      - composer install --ansi --no-suggest --no-progress -v
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  - name: site-install
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - ./vendor/bin/run drupal:site-install

  - name: run-test-with-grump
    group: test
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - ./vendor/bin/grumphp run

  - name: run-test-with-behat
    group: test
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    commands:
      - ./vendor/bin/behat --strict

  - name: slack
    image: plugins/slack
    settings:
      room: general
      webhook:
        from_secret: webhook_url
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job bobeh.
        {{else}}
          build {{build.number}} failed. Fix me please, bobeh.
        {{/success}}
    when:
      event: push
      status: [success, failure]
#      branch: master

matrix:
  PHP_VERSION:
  - 5.6
#  - 7.1
#  - 7.2
  COMPOSER_BOUNDARY:
  - lowest
#  - highest

trigger:
  event:
    - push
