workspace:
  base: /test
  path: bw_d7

services:
  web:
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    environment:
    - DOCUMENT_ROOT=/test/bw_d7
#  mysql:
#    image: percona/percona-server:5.6
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#  selenium:
#    image: selenium/standalone-chrome:3.11
#    environment:
#      - DISPLAY=:99
#      - SE_OPTS=-debug
pipeline:
  composer-install-lowest:
    group: prepare
    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
    volumes:
#      - /cache:/cache
    commands:
      - echo "testing WIP RUNNING STEP Composer-install-lowest"
      - composer install --ansi --no-suggest --no-progress -v
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

#  site-install:
#    image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
#    commands:
#      - ./vendor/bin/run drupal:site-install

  run-test-with-grump:
      group: test
      image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
      commands:
        - ./vendor/bin/grumphp run

#  run-test-with-behat:
#      group: test
#      image: fpfis/httpd-php-dev:${PHP_VERSION=5.6}
#      commands:
#        - ./vendor/bin/behat --strict

  slack:
    -name: slack
    image: plugins/slack
    settings:
      channel: tarafesonfire
      webhook: "https://hooks.slack.com/services/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"
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job bobeh.
        {{else}}
          build {{build.number}} failed. Fix me please, bobeh.
        {{/success}}

matrix:
  PHP_VERSION:
  - 5.6
#  - 7.1
#  - 7.2
  COMPOSER_BOUNDARY:
  - lowest
#  - highest

trigger:
  event:
    - push
